# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20160616_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instru',
            name='name',
        ),
        migrations.DeleteModel(
            name='Instru',
        ),
    ]
