# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20160616_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Long',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
