# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(blank=True)),
                ('endtime', models.TimeField(blank=True)),
                ('phone_num', models.CharField(max_length=11)),
                ('extro_info', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Instrument')),
            ],
        ),
        migrations.DeleteModel(
            name='Long',
        ),
    ]
