# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20160616_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instru',
            old_name='extro_info',
            new_name='extra_info',
        ),
    ]
