# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20160616_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instru',
            name='endtime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='instru',
            name='starttime',
            field=models.DateTimeField(blank=True),
        ),
    ]
