# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20160616_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
